version: '3.1'
services:
    GFS-client:
       image: gfs-client:v1
       container_name: glusterFs-client
       network_mode: host
       restart: always
       privileged: true
       extra_hosts:
         - "gfs1:172.16.106.130"
         - "gfs2:172.16.106.131"
         - "gfs3:172.16.106.132"
       volumes:
          - /etc/localtime:/etc/localtime
